# Molecule managed

---
all:
  hosts:
    centos-6: &id001
      ansible_connection: docker
    centos-7: &id002
      ansible_connection: docker
    debian-8: &id003
      ansible_connection: docker
    debian-9: &id004
      ansible_connection: docker
    ubuntu-14.04: &id005
      ansible_connection: docker
    ubuntu-16.04: &id006
      ansible_connection: docker
ungrouped:
  hosts:
    centos-6: *id001
    centos-7: *id002
    debian-8: *id003
    debian-9: *id004
    ubuntu-14.04: *id005
    ubuntu-16.04: *id006
  vars: {}
