---
- name: "setup sshd_config.conf"
  action: template src={{ item }} dest={{ sshd_file_config }} backup=yes owner=root group=root mode=0640
  with_first_found:
    - "sshd_config.{{ inventory_hostname }}.j2"
    - "sshd_config.{{ ansible_os_family }}.j2"
    - "sshd_config.default.j2"
  tags:
    - sshd
    - config
  notify:
    - restart sshd
