---
- name: "setup sshd_config.conf"
  template:
    src: "{{ item }}"
    dest: "{{ sshd_file_config }}"
    backup: yes
    owner: root
    group: root
    mode: 0640
    validate: "/usr/sbin/sshd -T -f %s"
  with_first_found:
    - "sshd_config.default.j2"
  notify:
    - restart sshd
