---
- name: "Common | setup sshd_config.conf"
  ansible.builtin.template:
    src: sshd_config.j2
    dest: "{{ sshd_file_config }}"
    backup: "{{ sshd_backup }}"
    owner: root
    group: root
    mode: 0640
    validate: "{{ sshd_binary }} -t -f %s"
  when: not sshd_test
  notify:
    - restart sshd

- name: "Common | setup sshd_config.conf"
  ansible.builtin.template:
    src: sshd_config.j2
    dest: "{{ sshd_file_config }}"
    backup: true
    owner: root
    group: root
    mode: 0640
  when: sshd_test
  notify:
    - restart sshd
