---
# tasks file for ssh

- name: "Common | set os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_os_family }}.yml"
  tags:
    - always

- name: "Include setup tasks"
  ansible.builtin.include_tasks: setup-{{ ansible_os_family }}.yml
  tags:
    - sshd
    - sshd:setup

- name: "Include ssh host key tasks"
  ansible.builtin.include_tasks: config-host_key.yml
  vars:
    host_key: "{{ sshd_host_key }}"
  with_items: "{{ sshd_host_keys_list }}"
  loop_control:
    loop_var: sshd_host_key
  tags:
    - sshd
    - sshd:config

- name: "Include config tasks"
  ansible.builtin.include_tasks: config.yml
  tags:
    - sshd
    - sshd:config

- name: "Include service tasks"
  ansible.builtin.include_tasks: service.yml
  tags:
    - sshd
    - sshd:service
