---
# tasks file for ssh

- name: "Common | set os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_os_family }}.yml"
  tags:
    - always

- name: "Include setup tasks"
  ansible.builtin.include_tasks:
    file: setup-{{ ansible_os_family }}.yml
    apply:
      tags:
        - sshd
        - sshd:setup
  tags:
    - always

- name: "Include ssh host key tasks"
  ansible.builtin.include_tasks:
    file: config-host_key.yml
    apply:
      tags:
        - sshd
        - sshd:config
  vars:
    host_key: "{{ sshd_host_key }}"
  with_items: "{{ sshd_host_keys_list }}"
  loop_control:
    loop_var: sshd_host_key
  tags:
    - always

- name: "Include config tasks"
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags:
        - sshd
        - sshd:config
  tags:
    - always

- name: "Include service tasks"
  ansible.builtin.include_tasks:
    file: service.yml
    apply:
      tags:
        - sshd
        - sshd:service
  tags:
    - always
