---
# tasks file for ssh

- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
   - "os-{{ ansible_distribution }}.yml"
   - "os-{{ ansible_os_family }}.yml"
  tags:
    - sshd
    - sshd:setup
    - sshd:config
    - sshd:service

# Debian(setup)  specific tasks
- include: setup-Debian.yml
  when: "ansible_os_family == 'Debian'"
  tags:
    - sshd
    - sshd:setup

# RedHat(setup) specific tasks
- include: setup-RedHat.yml
  when: "ansible_os_family == 'RedHat'"
  tags:
    - sshd
    - sshd:setup

# Suse(setup) specific tasks
- include: setup-Suse.yml
  when: "ansible_os_family == 'Suse'"
  tags:
    - sshd
    - sshd:setup

# Common configuration tasks tasks
- include: config.yml
  tags:
    - sshd
    - sshd:config

# Common service tasks
- include: service.yml
  tags:
    - sshd
    - sshd:service
