---
# tasks file for ssh

- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_os_family }}.yml"
  tags:
    - sshd
    - sshd:setup
    - sshd:config
    - sshd:service

- name: "include setup tasks"
  include: setup-{{ ansible_os_family }}.yml
  tags:
    - sshd
    - sshd:setup

- name: "include config tasks"
  include: config.yml
  tags:
    - sshd
    - sshd:config

- name: "include service tasks"
  include: service.yml
  tags:
    - sshd
    - sshd:service
