---
# tasks file for ssh

- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_os_family }}.yml"
  tags:
    - always

- name: "include setup tasks"
  include: setup-{{ ansible_os_family }}.yml
  tags:
    - sshd
    - sshd:setup

- name: "include ssh host key tasks"
  include: config-host_key.yml
  vars:
    host_key: "{{ sshd_host_key }}"
  with_items: "{{ sshd_host_keys_list }}"
  loop_control:
    loop_var: sshd_host_key
  tags:
    - sshd
    - sshd:config

- name: "include config tasks"
  include: config.yml
  tags:
    - sshd
    - sshd:config

- name: "include service tasks"
  include: service.yml
  tags:
    - sshd
    - sshd:service
