---
- name: "Common | ensure ssh started/stopped"
  ansible.builtin.service:
    name: "{{ sshd_service }}"
    state: "{{ sshd_service_state }}"
    enabled: "{{ sshd_service_enabled }}"
  when: not sshd_test
