---
- name: "Suse | check packages"
  community.general.packaging.os.zypper:
    pkg: "{{ package.name }}"
    state: "{{ package.state }}"
  with_items: "{{ sshd_packages }}"
  loop_control:
    loop_var: package
